// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewBab struct {
	Title   string       `json:"title"`
	Order   int          `json:"order"`
	SubBabs []*NewSubBab `json:"subBabs"`
}

type NewMaterial struct {
	Title            string `json:"title"`
	Order            int    `json:"order"`
	VideoURL         string `json:"videoURL"`
	AudioURL         string `json:"audioURL"`
	Text             string `json:"text"`
	DurationInMinute int    `json:"durationInMinute"`
}

type NewQuestion struct {
	Order    int      `json:"order"`
	Question string   `json:"question"`
	Options  []string `json:"options"`
	Hint     string   `json:"hint"`
	Answer   int      `json:"answer"`
}

type NewSubBab struct {
	Title          string `json:"title"`
	Order          int    `json:"order"`
	ImageURL       string `json:"imageURL"`
	InstructorName string `json:"instructorName"`
}

type NewTest struct {
	Title        string `json:"title"`
	Order        int    `json:"order"`
	MinimumScore int    `json:"minimumScore"`
}
